name: Remote Dispatch Action Initiator

on:
  push:
  
jobs:
  integration-test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository event
        run: |
          curl -X POST https://api.github.com/repos/Apollo-Core/IntegrationTests/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.IT_ACCESS_TOKEN }} \
          --data '{"event_type": "Push to '"$GITHUB_REPOSITORY"'", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'